url: https://aptanadev.github.io
baseurl: ""

# Site settings
title: SURYAPHONE
email: admin@salimphone.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
  - name: Kay Garland
    pic: 1
    position: Lead Designer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Larry Parker
    pic: 2
    position: Lead Marketer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Diana Petersen
    pic: 3
    position: Lead Developer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/suryaphonegroup/
  - title: instagram
    url: https://www.instagram.com/salimsuryaphone/
  # - title: file-audio-o
  #   url: https://www.tiktok.com/@suryaphone.official

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
